apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-stages
  namespace: ds
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: dynamic-stages
  template:
    metadata:
      labels:
        app: dynamic-stages
    spec:
      containers:
      - name: dynamic-stages
        image: image-registry.openshift-image-registry.svc:5000/ds/var-echo
        env:
          - name: LE_ENV_VAR
            value: asdf
        ports:
        - containerPort: 8080
