kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: dynamic-stage-{{ .Values.StageName }}
  namespace: ds
spec:
  source: 
    git:
      uri: "https://github.com/chtime/var-echo"
      ref: {{ .Values.Revision }}
  output: 
    to:
      kind: "ImageStreamTag"
      name: {{ printf "var-echo:%s" .Values.Revision }}