{{- range .Values.stages }}
apiVersion: v1
kind: Service
metadata:
  name: dynamic-stage-{{ .Values.name }}
  namespace: ds
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: dynamic-stage-{{ .Values.name }}
---
{{- end }}