apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo 
  namespace: argocd
spec:
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: '*'
  sourceRepos:
    - 'https://github.com/chtime/byi-oc'

