{{- range .Values.stages }}
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: dynamic-stage-{{ .name }}
  namespace: dynamic-stages
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  triggers:
    - type: "ConfigChange"
  source: 
    git:
      uri: "https://github.com/chtime/var-echo"
      ref: {{ .revision }}
  strategy:
    type: Docker
  output:
    to:
      kind: "ImageStreamTag"
      name: {{ printf "var-echo:%s" .revision }}
---
{{- end }}