kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: dynamic-stages
  namespace: ds
spec:
  triggers: 
    - type: "GitHub"
      github:
        secret: "secret101"
  source: 
    git:
      uri: "https://github.com/chtime/var-echo"
  output: 
    to:
      kind: "ImageStreamTag"
      name: "var-echo:latest"
