apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dynamic-stage-one
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chtime/byi-oc'
    targetRevision: main
    path: apps/dynamic-stage
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: 'ds'
  syncPolicy:
    automated: {}
  env:
  - name: LE_ENV_VAR
    value: env-var-on-dynamic-stage-one